---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetools-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kubetools
  template:
    metadata:
      labels:
        app: kubetools
    spec:
      serviceAccountName: kubetools
      pullPolicy: {{ .Values.image.pullPolicy }}
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
